### ISSUE TITLE
jsr305 issue in maven build

### ISSUE THREAD

**Issue by bbarker** [kciesielski/macmemo#9]
Hello,

I'm really looking forward to trying macmemo. Our project uses maven. 

I'm getting the following error when attempting to build:

```
[ERROR] Failed to execute goal on project dairy-econ: Could not resolve dependencies for project edu.cornell.ansci:dairy-econ:pom:0.0.1-SNAPSHOT: Failed to collect dependencies for [org.scala-lang:scala-compiler:jar:2.11.8 (compile), org.scala-lang:scala-library:jar:2.11.8 (compile), pl.metastack:metarx_2.11:jar:0.1.6 (compile), com.chuusai:shapeless_2.11:jar:2.3.2 (compile), com.softwaremill.macmemo:macros_2.11:jar:0.3 (compile), com.google.code.findbugs:jsr305:jar:1.3.0 (compile)]: No versions available for com.google.code.findbugs:jsr305:jar:[1.3,1.4) within specified range -> [Help 1]

```

I can't seem to find the right version (1.3 or 1.4) on maven central; I tried 1.3.9, as well as the latest (3.0.1) to no avail:
http://search.maven.org#search|gav|1|g%3A"com.google.code.findbugs"%20AND%20a%3A"jsr305"

I've tried with and without including the jsr305 dependency directly, and have tried deleting (`rm -fr ./repository/com/google/code/findbugs` ) the jsr305 directory and rerunning. 

Here are some relevant excerpts from my pom file:

```xml

...
      <scala.version.major>2.11</scala.version.major>
      <scala.version.minor>8</scala.version.minor>
      <scala.version>
          ${scala.version.major}.${scala.version.minor}
      </scala.version>
...

  <dependency>
    <groupId>com.chuusai</groupId>
    <artifactId>shapeless_${scala.version.major}</artifactId>
    <version>2.3.2</version>
  </dependency>

  <dependency>
    <groupId>com.softwaremill.macmemo</groupId>
    <artifactId>macros_${scala.version.major}</artifactId>
    <version>0.3</version>
  </dependency>

  <dependency>
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>jsr305</artifactId>
    <version>1.3.9</version>
  </dependency>

   ...
        <configuration>
          <compilerPlugins>
            <compilerPlugin>
              <groupId>org.scalamacros</groupId>
              <artifactId>paradise_${scala.version}</artifactId>
              <version>2.1.0</version>
            </compilerPlugin>
          </compilerPlugins>
        </configuration>
   ...
```

**Comment by kciesielski** [comment]
@bbarker thank you for reporting :) Could you create a minimal project setup so I could reproduce this issue?

**Comment by bbarker** [comment]
@kciesielski thanks, yes - here is one https://github.com/bbarker/macmemo-examples

IntelliJ picked up the issue in the pom file without the need for any actual source.

**Comment by kciesielski** [comment]
@bbarker Thank you for the example. Excluding jsr-305 from dependencies should help:

```xml
<dependency>
        <groupId>com.softwaremill.macmemo</groupId>
        <artifactId>macros_${scala.version.major}</artifactId>
        <version>0.3</version>
        <exclusions>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
        </exclusions>
</dependency>
```

By the way, I strongly encourage you to use sbt instead of maven if possible :)

**Comment by bbarker** [comment]
@kciesielski Thanks! didn't know about that ability in Maven. I am trying sbt on various projects, mostly small - I just converted this large one from Java to Scala (about 96%) over the last few months, and still have a few higher priorities before improving the build process - but I agree, sbt seems nicer from the little I know.
